_BASE_: ./CIS-R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  WEIGHTS: "pretrained/swin_small_patch4_window7_224.pth"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
OUTPUT_DIR: output/